pki:
  ca: /certs/ca.crt
  cert: /certs/client.crt
  key: /certs/client.key

static_host_map:
  "10.1.1.1":
    - "192.168.3.156:4242"

lighthouse:
  hosts:
    - "10.1.1.1"

listen:
  host: 0.0.0.0
  port: 4242

tun:
  dev: nebula1
  ip: 10.1.1.2/24

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from client
    - port: any
      proto: any
      host: any

  inbound:
    # Allow Nebula handshake and control traffic
    - port: 4242
      proto: udp
      host: any
